### ISSUE TITLE
Apps confusion

### ISSUE THREAD

**Issue by suyashjoshi** [ringcentral/trello-notification-app#26]
Hello,

While trying to find Trello integration with RingCentral, I found 3 such apps. Do you know what the difference is between the two published by RingCentral Labs ?

1. https://www.ringcentral.com/apps/trello-bot-for-ringcentral

2. https://www.ringcentral.com/apps/trello-beta-for-ringcentral

3. https://www.ringcentral.com/apps/trello-bot-ringcentral-video-kore-ai

Thanks!

**Comment by embbnux** [comment]
Hi @suyashjoshi For https://www.ringcentral.com/apps/trello-bot-for-ringcentral is implemented based on Bot add-in. The app work as a bot. 
For https://www.ringcentral.com/apps/trello-beta-for-ringcentral, the app is implemented on Notification add-in. 
We are thinking to deprecate notification add-in one.

The last app is built from old notification framework, not adaptive card support.

**Comment by suyashjoshi** [comment]
Thanks that helps.
